"""adiciona ordens de servico (fase 4)

Revision ID: 05305f4c6f5f
Revises: c1fb13af4044
Create Date: 2026-07-20 11:49:16.995203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05305f4c6f5f'
down_revision: Union[str, Sequence[str], None] = 'c1fb13af4044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('PREVENTIVA', 'CORRETIVA', name='service_order_type'), nullable=False),
    sa.Column('descricao', sa.String(length=2000), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='service_order_priority'), server_default='MEDIA', nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='service_order_status'), server_default='ABERTA', nullable=False),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('service_orders_one_open_per_equipamento', 'service_orders', ['equipamento_id'], unique=True, postgresql_where=sa.text("status IN ('ABERTA', 'EM_ANDAMENTO')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('service_orders_one_open_per_equipamento', table_name='service_orders', postgresql_where=sa.text("status IN ('ABERTA', 'EM_ANDAMENTO')"))
    op.drop_table('service_orders')
    # ### end Alembic commands ###
