"""estoque por filial (equipment_stock) e filial por item de contrato

Revision ID: 55274102ae44
Revises: 7a955fcca4cc
Create Date: 2026-07-21 01:52:20.375366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55274102ae44'
down_revision: Union[str, Sequence[str], None] = '7a955fcca4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `contract_items` ganha uma coluna NOT NULL (filial_id) sem um valor de
    # origem válido para backfill: nenhum equipamento existente tem filial_id
    # preenchido hoje (o campo era opcional), então não há como migrar as
    # reservas existentes para uma filial real. Como este projeto ainda está em
    # desenvolvimento e essas linhas são inteiramente dados de demonstração
    # reproduzíveis via `app/scripts/seed_demo_data.py`, limpamos a cadeia de
    # contratos/faturas/OS em vez de inventar uma filial fictícia — cadastros
    # base (equipment, clients, categorias, filiais, suppliers) são preservados.
    op.execute("DELETE FROM payments")
    op.execute("DELETE FROM invoice_items")
    op.execute("DELETE FROM invoices")
    op.execute("DELETE FROM service_orders")
    op.execute("DELETE FROM contract_amendments")
    op.execute("DELETE FROM contract_items")
    op.execute("DELETE FROM contracts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default='1', nullable=False),
    sa.Column('valor_diario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipamento_id', 'filial_id', name='uq_equipment_stock_equipamento_filial')
    )
    op.add_column('contract_items', sa.Column('filial_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_contract_items_filial_id', 'contract_items', 'filiais', ['filial_id'], ['id'])
    op.drop_constraint('fk_equipment_filial_id', 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'valor_diario')
    op.drop_column('equipment', 'valor_mensal')
    op.drop_column('equipment', 'valor_hora')
    op.drop_column('equipment', 'quantidade_total')
    op.drop_column('equipment', 'filial_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('filial_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('quantidade_total', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('valor_hora', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('valor_mensal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('valor_diario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_equipment_filial_id', 'equipment', 'filiais', ['filial_id'], ['id'])
    op.drop_constraint('fk_contract_items_filial_id', 'contract_items', type_='foreignkey')
    op.drop_column('contract_items', 'filial_id')
    op.drop_table('equipment_stock')
    # ### end Alembic commands ###
