"""adiciona confirmacao de assinatura via whatsapp ao contrato

Revision ID: 66da9c7a5e34
Revises: af37bd32585c
Create Date: 2026-07-22 14:23:21.235841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66da9c7a5e34'
down_revision: Union[str, Sequence[str], None] = 'af37bd32585c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE contract_signature_status AS ENUM "
        "('NAO_ENVIADO', 'AGUARDANDO_CONFIRMACAO', 'CONFIRMADO')"
    )
    op.add_column('contracts', sa.Column('assinatura_status', sa.Enum('NAO_ENVIADO', 'AGUARDANDO_CONFIRMACAO', 'CONFIRMADO', name='contract_signature_status'), server_default='NAO_ENVIADO', nullable=False))
    op.add_column('contracts', sa.Column('assinatura_mensagem_enviada', sa.String(length=2000), nullable=True))
    op.add_column('contracts', sa.Column('assinatura_enviada_em', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('assinatura_resposta_texto', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('assinatura_confirmada_em', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('assinatura_comprovante_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'assinatura_comprovante_key')
    op.drop_column('contracts', 'assinatura_confirmada_em')
    op.drop_column('contracts', 'assinatura_resposta_texto')
    op.drop_column('contracts', 'assinatura_enviada_em')
    op.drop_column('contracts', 'assinatura_mensagem_enviada')
    op.drop_column('contracts', 'assinatura_status')
    # ### end Alembic commands ###
    op.execute("DROP TYPE contract_signature_status")
