"""adiciona filiais, estoque e quantidade por item

Revision ID: 7a955fcca4cc
Revises: c6fd24209a99
Create Date: 2026-07-20 21:17:05.600850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a955fcca4cc'
down_revision: Union[str, Sequence[str], None] = 'c6fd24209a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=32), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('contract_items', sa.Column('quantidade', sa.Integer(), server_default='1', nullable=False))
    op.add_column('equipment', sa.Column('filial_id', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('quantidade_total', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('fk_equipment_filial_id', 'equipment', 'filiais', ['filial_id'], ['id'])
    # ### end Alembic commands ###

    # Remove a EXCLUDE constraint que garantia exclusividade de data por
    # equipamento: com quantidade_total > 1 (itens de estoque), múltiplos itens
    # do mesmo equipamento podem se sobrepor no período, desde que a soma das
    # quantidades não ultrapasse o estoque. Essa checagem passa a ser feita em
    # app/services/contract_service.py, com SELECT ... FOR UPDATE no equipamento
    # para permanecer segura sob concorrência (ver docs/regras-de-negocio.md).
    op.execute('ALTER TABLE contract_items DROP CONSTRAINT contract_items_no_overlap')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "ALTER TABLE contract_items ADD CONSTRAINT contract_items_no_overlap "
        "EXCLUDE USING gist (equipamento_id WITH =, daterange(data_inicio_item, data_fim_item, '[]') WITH &&) "
        "WHERE (status = 'ATIVO')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_equipment_filial_id', 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'quantidade_total')
    op.drop_column('equipment', 'filial_id')
    op.drop_column('contract_items', 'quantidade')
    op.drop_table('filiais')
    # ### end Alembic commands ###
