"""adiciona faturas, itens de fatura e pagamentos (fase 5)

Revision ID: a75d757dbd3e
Revises: cb875a434e72
Create Date: 2026-07-20 12:50:15.972522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75d757dbd3e'
down_revision: Union[str, Sequence[str], None] = 'cb875a434e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'ATRASADA', 'CANCELADA', name='invoice_status'), server_default='PENDENTE', nullable=False),
    sa.Column('multa_juros_aplicado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_nota_fiscal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('contract_item_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column com um enum novo não cria o tipo automaticamente (só
    # create_table faz isso) — precisa criar o tipo explicitamente antes.
    op.execute("CREATE TYPE billing_periodicity AS ENUM ('UNICA', 'MENSAL', 'DIARIA')")
    op.add_column('contracts', sa.Column('periodicidade_cobranca', sa.Enum('UNICA', 'MENSAL', 'DIARIA', name='billing_periodicity'), server_default='UNICA', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'periodicidade_cobranca')
    op.execute("DROP TYPE billing_periodicity")
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
