"""adiciona tabela message_templates

Revision ID: af37bd32585c
Revises: fa46aedae811
Create Date: 2026-07-22 12:37:07.582683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af37bd32585c'
down_revision: Union[str, Sequence[str], None] = 'fa46aedae811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.Enum('COBRANCA_FATURA', 'CONTRATO_ASSINATURA', name='template_key'), nullable=False),
    sa.Column('conteudo', sa.String(length=2000), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###

    # Seed dos templates default (mesmo texto que estava hardcoded em
    # invoice_service.py/contract_document_service.py antes desta fase).
    message_templates = sa.table(
        "message_templates",
        sa.column("chave", sa.String),
        sa.column("conteudo", sa.String),
    )
    op.bulk_insert(
        message_templates,
        [
            {
                "chave": "COBRANCA_FATURA",
                "conteudo": (
                    "Olá {cliente_nome}, tudo bem? Você tem uma fatura {situacao} no valor de "
                    "{valor}, com vencimento em {vencimento}.{multa_texto} Qualquer dúvida, "
                    "estamos à disposição!"
                ),
            },
            {
                "chave": "CONTRATO_ASSINATURA",
                "conteudo": (
                    "Olá {cliente_nome}, tudo bem? Segue o {tipo_contrato} #{contrato_id} para "
                    "sua análise e assinatura. Qualquer dúvida, estamos à disposição!"
                ),
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_templates')
    # ### end Alembic commands ###
