"""adiciona contratos, itens e aditivos (fase 3)

Revision ID: c1fb13af4044
Revises: edc5331b2536
Create Date: 2026-07-20 11:30:11.714628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1fb13af4044'
down_revision: Union[str, Sequence[str], None] = 'edc5331b2536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Necessário para o operador de igualdade de inteiro dentro de um índice GiST
    # (usado pelo EXCLUDE constraint de contract_items abaixo).
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'ATIVO', 'VENCIDO', 'ENCERRADO', 'CANCELADO', name='contract_status'), server_default='RASCUNHO', nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EXTENSAO', 'BAIXA_TOTAL', 'BAIXA_PARCIAL', 'CANCELAMENTO', name='contract_amendment_type'), nullable=False),
    sa.Column('data_anterior', sa.Date(), nullable=True),
    sa.Column('data_nova', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio_item', sa.Date(), nullable=False),
    sa.Column('data_fim_item', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'DEVOLVIDO', name='contract_item_status'), server_default='ATIVO', nullable=False),
    sa.Column('valor_item', sa.Numeric(precision=10, scale=2), nullable=True),
    postgresql.ExcludeConstraint((sa.text('equipamento_id'), '='), (sa.text("daterange(data_inicio_item, data_fim_item, '[]')"), '&&'), where=sa.text("status = 'ATIVO'"), using='gist', name='contract_items_no_overlap'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_items')
    op.drop_table('contract_amendments')
    op.drop_table('contracts')
    # ### end Alembic commands ###
