"""adiciona cobranca por hora (valor_hora, horas_trabalhadas, periodicidade hora)

Revision ID: c6fd24209a99
Revises: a75d757dbd3e
Create Date: 2026-07-20 16:14:34.656282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fd24209a99'
down_revision: Union[str, Sequence[str], None] = 'a75d757dbd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ALTER TYPE ... ADD VALUE não roda dentro de uma transação normal (autogenerate
    # não detecta esse tipo de mudança de qualquer forma — precisa ser manual).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE billing_periodicity ADD VALUE IF NOT EXISTS 'HORA'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_items', sa.Column('horas_trabalhadas', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('equipment', sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'valor_hora')
    op.drop_column('contract_items', 'horas_trabalhadas')
    # ### end Alembic commands ###
    # Não removemos o valor 'HORA' do enum billing_periodicity: Postgres não
    # suporta DROP VALUE em enums (exigiria recriar o tipo inteiro).
