"""adiciona campo fotos ao equipamento

Revision ID: cb875a434e72
Revises: fc197dda3f60
Create Date: 2026-07-20 12:17:15.511019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb875a434e72'
down_revision: Union[str, Sequence[str], None] = 'fc197dda3f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('fotos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'fotos')
    # ### end Alembic commands ###
