"""cadastros base: clients, equipment_categories, equipment

Revision ID: d690b9efcd4e
Revises: 
Create Date: 2026-07-20 10:43:32.289135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd690b9efcd4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PF', 'PJ', name='client_type'), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=False),
    sa.Column('telefone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('equipment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('modelo', sa.String(length=255), nullable=True),
    sa.Column('identificador', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'ALUGADO', 'MANUTENCAO', name='equipment_status'), server_default='DISPONIVEL', nullable=False),
    sa.Column('valor_diario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('atributos_extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['equipment_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('equipment_categories')
    op.drop_table('clients')
    # ### end Alembic commands ###
