"""adiciona inventory_movements (historico de estado do equipamento)

Revision ID: edc5331b2536
Revises: 23a6ab702c4c
Create Date: 2026-07-20 11:10:36.084628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'edc5331b2536'
down_revision: Union[str, Sequence[str], None] = '23a6ab702c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# tipo já existe (criado pela migration da tabela equipment); não recriar aqui
equipment_status_enum = postgresql.ENUM(
    'DISPONIVEL', 'RESERVADO', 'ALUGADO', 'MANUTENCAO', name='equipment_status', create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', equipment_status_enum, nullable=False),
    sa.Column('status_novo', equipment_status_enum, nullable=False),
    sa.Column('motivo', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
