"""adiciona valor_recorrente para contratos em aberto

Revision ID: fa46aedae811
Revises: 0e1bfbe5313d
Create Date: 2026-07-21 15:50:08.502811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa46aedae811'
down_revision: Union[str, Sequence[str], None] = '0e1bfbe5313d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('valor_recorrente', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'valor_recorrente')
    # ### end Alembic commands ###
